/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class NativeNormalizer */

#ifndef _Included_com_ibm_icu4jni_text_NativeNormalizer
#define _Included_com_ibm_icu4jni_text_NativeNormalizer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     NativeNormalizer
 * Method:    normalize
 * Signature: ([CII[CI)I
 */
JNIEXPORT jint JNICALL Java_com_ibm_icu4jni_text_NativeNormalizer_normalize
  (JNIEnv *, jclass, jcharArray, jint, jcharArray, jint, jint, jintArray);

JNIEXPORT jint JNICALL Java_com_ibm_icu4jni_text_NativeNormalizer_quickCheck
  (JNIEnv *, jclass, jcharArray, jint, jint, jintArray);

#ifdef __cplusplus
}
#endif
#endif
