/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ICUConverterInterface */

#ifndef _Included_com_ibm_icu4jni_converters_ICUConverterInterface
#define _Included_com_ibm_icu4jni_converters_ICUConverterInterface
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     com_ibm_icu4jni_converters_ICUConverterInterface
 * Method:    canConvert
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_com_ibm_icu4jni_converters_ICUConverterInterface_canConvert
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_ibm_icu4jni_converters_ICUConverterInterface
 * Method:    closeConverter
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_ibm_icu4jni_converters_ICUConverterInterface_closeConverter
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_ibm_icu4jni_converters_ICUConverterInterface
 * Method:    convertByteToChar
 * Signature: (J[BI[CI[IZ)I
 */
JNIEXPORT jint JNICALL Java_com_ibm_icu4jni_converters_ICUConverterInterface_convertByteToChar
  (JNIEnv *, jclass, jlong, jbyteArray, jint, jcharArray, jint, jintArray, jboolean);

/*
 * Class:     com_ibm_icu4jni_converters_ICUConverterInterface
 * Method:    convertCharToByte
 * Signature: (J[CI[BI[IZ)I
 */
JNIEXPORT jint JNICALL Java_com_ibm_icu4jni_converters_ICUConverterInterface_convertCharToByte
  (JNIEnv *, jclass, jlong, jcharArray, jint, jbyteArray, jint, jintArray, jboolean);

/*
 * Class:     com_ibm_icu4jni_converters_ICUConverterInterface
 * Method:    countInvalidBytes
 * Signature: (J[I)I
 */
JNIEXPORT jint JNICALL Java_com_ibm_icu4jni_converters_ICUConverterInterface_countInvalidBytes
  (JNIEnv *, jclass, jlong, jintArray);

/*
 * Class:     com_ibm_icu4jni_converters_ICUConverterInterface
 * Method:    countInvalidChars
 * Signature: (J[I)I
 */
JNIEXPORT jint JNICALL Java_com_ibm_icu4jni_converters_ICUConverterInterface_countInvalidChars
  (JNIEnv *, jclass, jlong, jintArray);

/*
 * Class:     com_ibm_icu4jni_converters_ICUConverterInterface
 * Method:    flushByteToChar
 * Signature: (J[CI[I)I
 */
JNIEXPORT jint JNICALL Java_com_ibm_icu4jni_converters_ICUConverterInterface_flushByteToChar
  (JNIEnv *, jclass, jlong, jcharArray, jint, jintArray);

/*
 * Class:     com_ibm_icu4jni_converters_ICUConverterInterface
 * Method:    flushCharToByte
 * Signature: (J[BI[I)I
 */
JNIEXPORT jint JNICALL Java_com_ibm_icu4jni_converters_ICUConverterInterface_flushCharToByte
  (JNIEnv *, jclass, jlong, jbyteArray, jint, jintArray);

/*
 * Class:     com_ibm_icu4jni_converters_ICUConverterInterface
 * Method:    getMaxBytesPerChar
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_ibm_icu4jni_converters_ICUConverterInterface_getMaxBytesPerChar
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_ibm_icu4jni_converters_ICUConverterInterface
 * Method:    openConverter
 * Signature: ([JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_ibm_icu4jni_converters_ICUConverterInterface_openConverter
  (JNIEnv *, jclass, jlongArray, jstring);

/*
 * Class:     com_ibm_icu4jni_converters_ICUConverterInterface
 * Method:    resetByteToChar
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_ibm_icu4jni_converters_ICUConverterInterface_resetByteToChar
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_ibm_icu4jni_converters_ICUConverterInterface
 * Method:    resetCharToByte
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_ibm_icu4jni_converters_ICUConverterInterface_resetCharToByte
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_ibm_icu4jni_converters_ICUConverterInterface
 * Method:    setSubstitutionBytes
 * Signature: (J[BI)I
 */
JNIEXPORT jint JNICALL Java_com_ibm_icu4jni_converters_ICUConverterInterface_setSubstitutionBytes
  (JNIEnv *, jclass, jlong, jbyteArray, jint);

/*
 * Class:     com_ibm_icu4jni_converters_ICUConverterInterface
 * Method:    setSubstitutionChars
 * Signature: (J[CI)I
 */
JNIEXPORT jint JNICALL Java_com_ibm_icu4jni_converters_ICUConverterInterface_setSubstitutionChars
  (JNIEnv *, jclass, jlong, jcharArray, jint);

/*
 * Class:     com_ibm_icu4jni_converters_ICUConverterInterface
 * Method:    setSubstitutionModeCharToByte
 * Signature: (JZ)I
 */
JNIEXPORT jint JNICALL Java_com_ibm_icu4jni_converters_ICUConverterInterface_setSubstitutionModeCharToByte
  (JNIEnv *, jclass, jlong, jboolean);

#ifdef __cplusplus
}
#endif
#endif
